<template>
<div class="page-section"><div class="home-card"><div class="card-header"><span class="card-title"><span class="title-dot"></span>三助一辅</span></div><div class="card-body"><el-tabs type="border-card">
<el-tab-pane label="岗位申请"><el-button type="primary" size="small" round style="margin-bottom:12px" @click="openAdd('apply')">申请岗位</el-button><el-table :data="apps" size="small" stripe empty-text="暂无数据"><el-table-column prop="post" label="岗位" min-width="160"/><el-table-column prop="dept" label="部门" width="130"/><el-table-column prop="type" label="类别" width="80"><template #default><el-tag size="small" round>助教</el-tag></template></el-table-column><el-table-column prop="date" label="日期" width="110"/><el-table-column prop="status" label="状态" width="90"><template #default><el-tag type="success" size="small" round>已通过</el-tag></template></el-table-column><el-table-column label="操作" width="180"><template #default="{row}"><span class="btn-row"><el-button text type="primary" size="small" @click="viewDetail(row)">详情</el-button><el-button text type="danger" size="small" @click="apps=apps.filter(a=>a.id!==row.id)">删除</el-button><el-button text type="success" size="small" @click="handlePrint(row)">打印</el-button></span></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="退岗申请"><el-button type="primary" size="small" round style="margin-bottom:12px" @click="openAdd('resign')">退岗申请</el-button><el-table :data="resigns" size="small" stripe empty-text="暂无数据"><el-table-column prop="post" label="岗位" min-width="160"/><el-table-column prop="reason" label="原因" min-width="180"/><el-table-column prop="date" label="日期" width="110"/><el-table-column prop="status" label="状态" width="90"><template #default><el-tag type="success" size="small" round>已批准</el-tag></template></el-table-column><el-table-column label="操作" width="180"><template #default="{row}"><span class="btn-row"><el-button text type="primary" size="small" @click="viewDetail(row)">详情</el-button><el-button text type="danger" size="small" @click="resigns=resigns.filter(r=>r.id!==row.id)">删除</el-button><el-button text type="success" size="small" @click="handlePrint(row)">打印</el-button></span></template></el-table-column></el-table></el-tab-pane>
</el-tabs>

<el-dialog v-model="dlg.show" :title="dlg.title" width="580px"><el-descriptions v-if="dlg.mode==='view'" :column="2" border size="small"><el-descriptions-item v-for="(v,k) in dlg.row" :key="k" :label="String(k)"><span>{{v||'-'}}</span></el-descriptions-item></el-descriptions><el-form v-else :model="dlg.row" label-width="90px"><el-form-item label="岗位名称"><el-input v-model="dlg.row.post"/></el-form-item><el-form-item label="部门"><el-input v-model="dlg.row.dept"/></el-form-item><el-form-item label="类别"><el-select v-model="dlg.row.type" style="width:100%"><el-option label="助教" value="助教"/><el-option label="助管" value="助管"/><el-option label="助研" value="助研"/><el-option label="一辅" value="一辅"/></el-select></el-form-item></el-form><template #footer><span v-if="dlg.mode==='view'"><el-button type="success" @click="handlePrint(dlg.row)">打印</el-button><el-button @click="dlg.show=false">关闭</el-button></span><span v-else><el-button @click="dlg.mode='view'">取消</el-button><el-button type="primary" @click="saveData">保存</el-button></span></template></el-dialog>
</div></div></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {usePrint} from '@/composables/usePrint'
const {doPrint}=usePrint()
const apps=ref([{id:1,post:'研究生助教',dept:'计算机学院',date:'2026-02-20',status:'已通过',type:'助教'},{id:2,post:'实验室管理员助理',dept:'实验中心',date:'2026-03-01',status:'审核中',type:'助管'}])
const resigns=ref([{id:1,post:'图书馆管理员助理',reason:'学业繁忙',date:'2025-12-15',status:'已批准'}])
const dlg=reactive({show:false,title:'',mode:'view',row:{} as any})
function viewDetail(row:any){dlg.row={...row};dlg.title='详情';dlg.mode='view';dlg.show=true}
function openAdd(tab:string){if(tab==='apply'){const r={id:Date.now(),post:'',dept:'',date:new Date().toISOString().split('T')[0],status:'审核中',type:'助教'};apps.value.unshift(r);dlg.row=r;dlg.title='岗位申请';dlg.mode='edit'}else{const r={id:Date.now(),post:'',reason:'',date:new Date().toISOString().split('T')[0],status:'审核中'};resigns.value.unshift(r);dlg.row=r;dlg.title='退岗申请';dlg.mode='edit'};dlg.show=true}
function saveData(){dlg.show=false}
function handlePrint(row:any){doPrint('三助一辅',row,{post:'岗位',dept:'部门',date:'日期',status:'状态',type:'类别',reason:'原因'})}
</script>
<style scoped>.page-section{max-width:1000px}.btn-row{display:inline-flex;align-items:center;gap:2px;white-space:nowrap}</style>
