<template>
<div class="page-section"><div class="home-card"><div class="card-header"><span class="card-title"><span class="title-dot"></span>困难申请</span><el-button type="primary" size="small" round @click="openAdd">新增申请</el-button></div><div class="card-body"><el-table :data="apps" size="small" stripe empty-text="暂无数据"><el-table-column prop="type" label="类型" width="130"/><el-table-column prop="reason" label="原因" min-width="200"/><el-table-column prop="date" label="日期" width="110"/><el-table-column prop="status" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='已通过'?'success':'warning'" size="small" round>{{row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="200"><template #default="{row}"><span class="btn-row"><el-button text type="primary" size="small" @click="viewDetail(row)">详情</el-button><el-button text type="warning" size="small" @click="editRow(row)">编辑</el-button><el-button text type="danger" size="small" @click="apps=apps.filter(a=>a.id!==row.id)">删除</el-button><el-button text type="success" size="small" @click="handlePrint(row)">打印</el-button></span></template></el-table-column></el-table>
<el-dialog v-model="dlg.show" :title="dlg.title" width="550px"><el-descriptions v-if="dlg.mode==='view'" :column="2" border size="small"><el-descriptions-item label="类型">{{dlg.row.type}}</el-descriptions-item><el-descriptions-item label="日期">{{dlg.row.date}}</el-descriptions-item><el-descriptions-item label="状态">{{dlg.row.status}}</el-descriptions-item><el-descriptions-item label="原因" :span="2">{{dlg.row.reason}}</el-descriptions-item></el-descriptions><el-form v-else :model="dlg.row" label-width="90px"><el-form-item label="困难类型"><el-select v-model="dlg.row.type" style="width:100%"><el-option label="家庭经济困难" value="家庭经济困难"/><el-option label="突发困难" value="突发困难"/><el-option label="临时困难" value="临时困难"/></el-select></el-form-item><el-form-item label="申请原因"><el-input v-model="dlg.row.reason" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><span v-if="dlg.mode==='view'"><el-button type="warning" @click="dlg.mode='edit'">编辑</el-button><el-button type="success" @click="handlePrint(dlg.row)">打印</el-button><el-button @click="dlg.show=false">关闭</el-button></span><span v-else><el-button @click="dlg.mode='view'">取消</el-button><el-button type="primary" @click="saveEdit">保存</el-button></span></template></el-dialog></div></div></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {ElMessage} from 'element-plus';import {usePrint} from '@/composables/usePrint'
const {doPrint}=usePrint()
const apps=ref([{id:1,type:'家庭经济困难',reason:'家庭收入较低，难以承担学费',date:'2025-09-15',status:'已通过'}])
const dlg=reactive({show:false,title:'',mode:'view',row:{} as any})
function viewDetail(row:any){dlg.row={...row};dlg.title='详情';dlg.mode='view';dlg.show=true}
function editRow(row:any){dlg.row={...row};dlg.title='编辑';dlg.mode='edit';dlg.show=true}
function openAdd(){dlg.row={id:Date.now(),type:'家庭经济困难',reason:'',date:new Date().toISOString().split('T')[0],status:'审核中'};dlg.title='新增申请';dlg.mode='edit';dlg.show=true}
function saveEdit(){const idx=apps.value.findIndex(a=>a.id===dlg.row.id);if(idx>=0)apps.value[idx]=dlg.row;else apps.value.unshift(dlg.row);dlg.show=false;ElMessage.success('保存成功')}
function handlePrint(row:any){doPrint('困难申请表',row,{type:'类型',reason:'原因',date:'日期',status:'状态'})}
</script>
<style scoped>.page-section{max-width:800px}.btn-row{display:inline-flex;align-items:center;gap:2px;white-space:nowrap}</style>
