<template>
<div class="page-section"><div class="home-card"><div class="card-header"><span class="card-title"><span class="title-dot"></span>助学贷款</span><el-button type="primary" size="small" round @click="openAdd">贷款申请</el-button></div><div class="card-body"><el-table :data="loans" size="small" stripe empty-text="暂无数据"><el-table-column prop="type" label="类型" width="140"/><el-table-column prop="amount" label="金额(元)" width="110"/><el-table-column prop="bank" label="银行" width="150"/><el-table-column prop="date" label="日期" width="110"/><el-table-column prop="status" label="状态" width="90"><template #default><el-tag type="success" size="small" round>已通过</el-tag></template></el-table-column><el-table-column label="操作" width="230"><template #default="{row}"><span class="btn-row"><el-button text type="primary" size="small" @click="viewDetail(row)">详情</el-button><el-button text type="warning" size="small" @click="editRow(row)">编辑</el-button><el-button text type="danger" size="small" @click="loans=loans.filter(l=>l.id!==row.id)">删除</el-button><el-button text type="success" size="small" @click="handlePrint(row)">打印</el-button></span></template></el-table-column></el-table>
<el-dialog v-model="dlg.show" :title="dlg.title" width="550px"><el-descriptions v-if="dlg.mode==='view'" :column="2" border size="small"><el-descriptions-item label="贷款类型">{{dlg.row.type}}</el-descriptions-item><el-descriptions-item label="金额">{{dlg.row.amount}}</el-descriptions-item><el-descriptions-item label="银行">{{dlg.row.bank}}</el-descriptions-item><el-descriptions-item label="日期">{{dlg.row.date}}</el-descriptions-item><el-descriptions-item label="状态">{{dlg.row.status}}</el-descriptions-item></el-descriptions><el-form v-else :model="dlg.row" label-width="90px"><el-form-item label="贷款类型"><el-select v-model="dlg.row.type" style="width:100%"><el-option label="国家助学贷款" value="国家助学贷款"/><el-option label="生源地贷款" value="生源地贷款"/></el-select></el-form-item><el-form-item label="金额(元)"><el-input-number v-model="dlg.row.amount" :min="0" :step="1000" style="width:100%"/></el-form-item><el-form-item label="银行"><el-input v-model="dlg.row.bank"/></el-form-item></el-form><template #footer><span v-if="dlg.mode==='view'"><el-button type="warning" @click="dlg.mode='edit'">编辑</el-button><el-button type="success" @click="handlePrint(dlg.row)">打印</el-button><el-button @click="dlg.show=false">关闭</el-button></span><span v-else><el-button @click="dlg.mode='view'">取消</el-button><el-button type="primary" @click="saveEdit">保存</el-button></span></template></el-dialog></div></div></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import {ElMessage} from 'element-plus';import {usePrint} from '@/composables/usePrint'
const {doPrint}=usePrint()
const loans=ref([{id:1,type:'国家助学贷款',amount:12000,bank:'中国银行',date:'2025-09-10',status:'已通过'}])
const dlg=reactive({show:false,title:'',mode:'view',row:{} as any})
function viewDetail(row:any){dlg.row={...row};dlg.title='详情';dlg.mode='view';dlg.show=true}
function editRow(row:any){dlg.row={...row};dlg.title='编辑';dlg.mode='edit';dlg.show=true}
function openAdd(){dlg.row={id:Date.now(),type:'国家助学贷款',amount:0,bank:'',date:new Date().toISOString().split('T')[0],status:'审核中'};dlg.title='贷款申请';dlg.mode='edit';dlg.show=true}
function saveEdit(){const idx=loans.value.findIndex(l=>l.id===dlg.row.id);if(idx>=0)loans.value[idx]=dlg.row;else loans.value.unshift(dlg.row);dlg.show=false;ElMessage.success('保存成功')}
function handlePrint(row:any){doPrint('助学贷款申请表',row,{type:'贷款类型',amount:'金额(元)',bank:'银行',date:'日期',status:'状态'})}
</script>
<style scoped>.page-section{max-width:900px}.btn-row{display:inline-flex;align-items:center;gap:2px;white-space:nowrap}</style>
