<template>
<div class="page-section"><div class="home-card"><div class="card-header"><span class="card-title"><span class="title-dot"></span>项目管理</span><el-button type="primary" size="small" round @click="openAdd">新增</el-button></div><div class="card-body"><el-table :data="rows" size="small" stripe empty-text="暂无数据"><el-table-column prop="name" label="项目名称" min-width="240"/><el-table-column prop="source" label="来源" width="150"/><el-table-column prop="fund" label="经费" width="70"/><el-table-column prop="deadline" label="截止" width="110"/><el-table-column label="进度" width="100"><template #default="scope"><el-progress :percentage="parseInt(scope.row.progress)||0" :stroke-width="10"/></template></el-table-column><el-table-column prop="status" label="状态" width="80"><template #default="scope"><el-tag type="success" size="small" round>{{scope.row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="260" fixed="right"><template #default="scope"><span class="btn-row"><el-button text type="primary" size="small" @click="viewDetail(scope.row)">详情</el-button><el-button text type="warning" size="small" @click="editRow(scope.row)">编辑</el-button><el-button text type="danger" size="small" @click="deleteRow(scope.row)">删除</el-button><el-button text type="success" size="small" @click="doPrint(scope.row)">打印</el-button></span></template></el-table-column></el-table>
<el-dialog v-model="dlg.show" :title="dlg.title" width="620px"><el-descriptions v-if="dlg.mode==='view'" :column="2" border size="small"><el-descriptions-item v-for="f in dlgFields" :key="f.key" :label="f.label"><span>{{dlg.row[f.key]||'-'}}</span></el-descriptions-item></el-descriptions><el-form v-else :model="dlg.row" label-width="90px"><el-form-item v-for="f in dlgFields" :key="f.key" :label="f.label"><el-input v-model="dlg.row[f.key]"/></el-form-item></el-form><template #footer><span v-if="dlg.mode==='view'"><el-button type="warning" @click="dlg.mode='edit'">编辑</el-button><el-button type="success" @click="doPrint(dlg.row)">打印</el-button><el-button @click="dlg.show=false">关闭</el-button></span><span v-else><el-button @click="dlg.mode='view'">取消</el-button><el-button type="primary" @click="saveEdit">保存</el-button></span></template></el-dialog></div></div></div></template>
<script setup lang="ts">
import {ref,reactive} from 'vue';import {ElMessage,ElMessageBox} from 'element-plus';import {usePrint} from '@/composables/usePrint'
const {doPrint}=usePrint()
const dlgFields=[{key:"name",label:"项目名称"},{key:"source",label:"来源"},{key:"fund",label:"经费"},{key:"deadline",label:"截止日期"},{key:"progress",label:"进度"},{key:"status",label:"状态"}];
const rows=ref([{name:"大规模图神经网络训练优化",source:"国家自然科学基金",fund:"58万",deadline:"2027-12-31",progress:"65",status:"在研"},
{name:"多模态数据融合分析平台",source:"省科技厅重点研发",fund:"30万",deadline:"2026-12-31",progress:"40",status:"在研"}]);
const dlg=reactive({show:false,title:'',mode:'view',row:{} as any})
function viewDetail(row:any){dlg.row={...row};dlg.title='详情';dlg.mode='view';dlg.show=true}
function editRow(row:any){dlg.row={...row};dlg.title='编辑';dlg.mode='edit';dlg.show=true}
function openAdd(){dlg.row={id:Date.now(),name:"",source:"",fund:"",deadline:"",progress:"0",status:"在研"};dlg.title='新增';dlg.mode='edit';dlg.show=true}
function saveEdit(){const idx=rows.value.findIndex((r:any)=>r.id===dlg.row.id);if(idx>=0)rows.value[idx]=dlg.row;else rows.value.unshift(dlg.row);dlg.show=false;ElMessage.success('保存成功')}
function deleteRow(row:any){ElMessageBox.confirm('确认删除？','确认',{type:'warning'}).then(()=>{rows.value=rows.value.filter((r:any)=>r.id!==row.id);ElMessage.success('已删除')})}
</script>
<style scoped>.page-section{max-width:1200px}.btn-row{display:inline-flex;align-items:center;gap:1px;white-space:nowrap}</style>