<template>
<div class="page-section"><div class="home-card"><div class="card-header"><span class="card-title"><span class="title-dot"></span>个人信息</span></div><div class="card-body"><el-tabs type="border-card">
<el-tab-pane label="基本信息"><el-form :model="form" label-width="100px"><el-row :gutter="20"><el-col :span="12"><el-form-item label="学号"><el-input v-model="form.id" disabled/></el-form-item><el-form-item label="姓名"><el-input v-model="form.name" disabled/></el-form-item><el-form-item label="性别"><el-radio-group v-model="form.gender" disabled><el-radio value="male">男</el-radio></el-radio-group></el-form-item><el-form-item label="出生日期"><el-input v-model="form.birth" disabled/></el-form-item><el-form-item label="民族"><el-input v-model="form.ethnic" disabled/></el-form-item><el-form-item label="政治面貌"><el-input v-model="form.political" disabled/></el-form-item></el-col><el-col :span="12"><el-form-item label="身份证"><el-input v-model="form.idcard" disabled/></el-form-item><el-form-item label="学院"><el-input v-model="form.college" disabled/></el-form-item><el-form-item label="专业"><el-input v-model="form.major" disabled/></el-form-item><el-form-item label="导师"><el-input v-model="form.advisor" disabled/></el-form-item><el-form-item label="入学日期"><el-input v-model="form.enroll" disabled/></el-form-item><el-form-item label="学制"><el-input v-model="form.duration" disabled/></el-form-item></el-col></el-row><el-divider/><el-form-item label="手机"><el-input v-model="form.phone"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item label="家庭地址"><el-input v-model="form.address" type="textarea" :rows="2"/></el-form-item><el-form-item><el-button type="primary" round @click="save">保存修改</el-button><el-button round @click="handlePrint">打印信息</el-button></el-form-item></el-form></el-tab-pane>
<el-tab-pane label="学籍信息"><el-descriptions :column="2" border><el-descriptions-item label="学号">2023301001</el-descriptions-item><el-descriptions-item label="姓名">张三</el-descriptions-item><el-descriptions-item label="培养层次">硕士研究生</el-descriptions-item><el-descriptions-item label="学习形式">全日制</el-descriptions-item><el-descriptions-item label="入学年份">2023</el-descriptions-item><el-descriptions-item label="预计毕业">2026</el-descriptions-item><el-descriptions-item label="学制">3年</el-descriptions-item><el-descriptions-item label="学籍状态"><el-tag type="success" round>在籍</el-tag></el-descriptions-item></el-descriptions></el-tab-pane>
</el-tabs>

<el-dialog v-model="printShow" title="个人信息打印" width="600px"><div style="text-align:center"><h3 style="color:#153D97;margin-bottom:16px">个人信息表</h3><table style="width:100%;border-collapse:collapse;font-size:13px"><tr v-for="(v,k) in form" :key="k" style="border-bottom:1px solid #f0f0f0"><td style="padding:8px 12px;font-weight:600;width:120px;background:#f8fafc">{{fieldLabels[k]||k}}</td><td style="padding:8px 12px">{{v||'-'}}</td></tr></table><p style="margin-top:20px;color:#94a3b8;font-size:11px">{{new Date().toLocaleString()}}</p></div><template #footer><el-button type="primary" @click="window.print()">打印</el-button><el-button @click="printShow=false">关闭</el-button></template></el-dialog>
</div></div></div></template>
<script setup lang="ts">
import {reactive,ref} from 'vue';import {ElMessage as $m} from 'element-plus';
const form=reactive({id:'2023301001',name:'张三',gender:'male',birth:'2000-03-15',ethnic:'汉族',political:'共青团员',idcard:'32010220000315****',college:'计算机学院',major:'计算机科学与技术',advisor:'李教授',enroll:'2023-09-01',duration:'3年',phone:'13800138000',email:'zhangsan@cqupt.edu.cn',address:'江苏省南京市鼓楼区XX路XX号'})
// removed:Record<string,string>={id:'学号',name:'姓名',gender:'性别',birth:'出生日期',ethnic:'民族',political:'政治面貌',idcard:'身份证号',college:'学院',major:'专业',advisor:'导师',enroll:'入学日期',duration:'学制',phone:'手机',email:'邮箱',address:'家庭地址'}

function save(){$m({message:'个人信息保存成功',type:'success'})}
function handlePrint(){doPrint("个人信息表",form,{id:"学号",name:"姓名",gender:"性别",birth:"出生日期",ethnic:"民族",political:"政治面貌",idcard:"身份证号",college:"学院",major:"专业",advisor:"导师",enroll:"入学日期",duration:"学制",phone:"手机",email:"邮箱",address:"家庭地址"})}
</script>
<style scoped>.page-section{max-width:1000px}</style>
