<template>
<div class="page-section"><div class="home-card"><div class="card-header"><span class="card-title"><span class="title-dot"></span>培养管理</span></div><div class="card-body"><el-tabs type="border-card">
<el-tab-pane label="学期注册"><el-button type="primary" size="small" round style="margin-bottom:12px" @click="openRegister">学期注册</el-button><el-table :data="registers" size="small" stripe empty-text="暂无注册记录"><el-table-column prop="semester" label="学期" min-width="200"/><el-table-column label="状态" width="120"><template #default="{row}"><el-tag :type="row.status==='已注册'?'success':'warning'" size="small" round>{{row.status}}</el-tag></template></el-table-column><el-table-column prop="date" label="注册时间" width="140"/><el-table-column label="操作" width="200"><template #default="{row}"><el-button text type="primary" size="small" @click="viewReg(row)">详情</el-button><el-button v-if="row.status==='待注册'" type="primary" size="small" round @click="row.status='已注册';row.date=new Date().toISOString().split('T')[0]">注册</el-button><el-button text type="success" size="small" @click="printReg(row)">打印</el-button></template></el-table-column></el-table><el-pagination style="margin-top:12px;justify-content:center" background layout="prev,next" :total="registers.length" :page-size="10"/></el-tab-pane>
<el-tab-pane label="培养计划"><el-button type="primary" size="small" round style="margin-bottom:12px" @click="openPlanNew">添加课程</el-button><el-table :data="planItems" size="small" stripe empty-text="暂无计划"><el-table-column prop="course" label="课程" min-width="180"/><el-table-column prop="credits" label="学分" width="60"/><el-table-column label="类别" width="100"><template #default="{row}"><el-tag size="small" round>{{row.type}}</el-tag></template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='已完成'?'success':'info'" size="small" round>{{row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="160"><template #default="{row}"><el-button text type="primary" size="small" @click="viewPlan(row)">详情</el-button><el-button text type="warning" size="small" @click="editPlan(row)">编辑</el-button><el-button text type="danger" size="small" @click="planItems=planItems.filter(p=>p.id!==row.id)">删除</el-button></template></el-table-column></el-table><div style="margin-top:12px;text-align:right;font-weight:600">已修: {{completedCredits}} / 要求: 32</div></el-tab-pane>
<el-tab-pane label="变更导师"><el-button type="primary" size="small" round style="margin-bottom:12px" @click="openAdvisor">发起申请</el-button><el-table :data="advisorChanges" size="small" stripe empty-text="暂无记录"><el-table-column prop="date" label="日期" width="120"/><el-table-column prop="old" label="原导师" width="100"/><el-table-column prop="new" label="新导师" width="100"/><el-table-column prop="reason" label="原因" min-width="180"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='已通过'?'success':'warning'" size="small" round>{{row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="120"><template #default="{row}"><el-button text type="primary" size="small" @click="viewAdvisor(row)">详情</el-button><el-button text type="success" size="small" @click="printReg(row)">打印</el-button></template></el-table-column></el-table></el-tab-pane>
</el-tabs>

<el-dialog v-model="dlg.show" :title="dlg.title" width="550px"><el-descriptions v-if="dlg.mode==='view'" :column="2" border size="small"><el-descriptions-item v-for="(v,k) in dlg.data" :key="k" :label="String(k)"><span>{{v||'-'}}</span></el-descriptions-item></el-descriptions><div v-else-if="dlg.mode==='print'" style="text-align:center"><h3 style="color:#153D97;margin-bottom:16px">{{dlg.title}}</h3><table style="width:100%;border-collapse:collapse;font-size:13px"><tr v-for="(v,k) in dlg.data" :key="k" style="border-bottom:1px solid #f0f0f0"><td style="padding:8px 12px;font-weight:600;width:120px;background:#f8fafc">{{k}}</td><td style="padding:8px 12px">{{v||'-'}}</td></tr></table></div><template #footer><el-button v-if="dlg.mode==='print'" type="primary" @click="window.print()">打印</el-button><el-button @click="dlg.show=false">关闭</el-button></template></el-dialog>

<el-dialog v-model="planDlg.show" :title="planDlg.title" width="500px"><el-form :model="planDlg.form" label-width="80px"><el-form-item label="课程名称"><el-input v-model="planDlg.form.course"/></el-form-item><el-form-item label="学分"><el-input-number v-model="planDlg.form.credits" :min="0.5" :max="10" :step="0.5"/></el-form-item><el-form-item label="类别"><el-select v-model="planDlg.form.type" style="width:100%"><el-option label="学位课" value="学位课"/><el-option label="公共课" value="公共课"/><el-option label="选修课" value="选修课"/></el-select></el-form-item></el-form><template #footer><el-button @click="planDlg.show=false">取消</el-button><el-button type="primary" @click="savePlan">保存</el-button></template></el-dialog>
</div></div></div></template>
<script setup lang="ts">
import {ref,reactive,computed} from 'vue'
const registers=ref([{semester:'2025-2026学年第二学期',status:'已注册',date:'2026-02-20',location:'线上注册'},{semester:'2025-2026学年第一学期',status:'已注册',date:'2025-09-05',location:'计算机学院学工办'}])
const planItems=ref([{id:1,course:'高级算法设计与分析',credits:3,type:'学位课',semester:'2025-2026-1',status:'已完成'},{id:2,course:'机器学习理论',credits:2,type:'学位课',semester:'2025-2026-1',status:'已完成'},{id:3,course:'学术英语写作',credits:2,type:'公共课',semester:'2025-2026-1',status:'已完成'},{id:4,course:'自然语言处理',credits:2,type:'选修课',semester:'2025-2026-2',status:'进行中'}])
const advisorChanges=ref([{date:'2025-11-10',old:'张教授',new:'李教授',reason:'研究方向调整',status:'已通过'}])
const completedCredits=computed(()=>planItems.value.filter(p=>p.status==='已完成').reduce((s,p)=>s+p.credits,0))
const dlg=reactive({show:false,title:'',mode:'view',data:{} as any})
function viewReg(row:any){dlg.data=row;dlg.title='注册详情';dlg.mode='view';dlg.show=true}
function printReg(row:any){dlg.data=row;dlg.title='打印';dlg.mode='print';dlg.show=true}
function viewPlan(row:any){dlg.data=row;dlg.title='课程详情';dlg.mode='view';dlg.show=true}
function viewAdvisor(row:any){dlg.data=row;dlg.title='申请详情';dlg.mode='view';dlg.show=true}
function openRegister(){const r={semester:'2026-2027学年第一学期',status:'待注册',date:'',location:'线上注册'};registers.value.unshift(r)}
const planDlg=reactive({show:false,title:'',form:{course:'',credits:2,type:'学位课'},editingId:0 as number})
function openPlanNew(){planDlg.title='添加课程';planDlg.form={course:'',credits:2,type:'学位课'};planDlg.editingId=0;planDlg.show=true}
function editPlan(row:any){planDlg.title='编辑课程';planDlg.form={...row};planDlg.editingId=row.id;planDlg.show=true}
function savePlan(){if(planDlg.editingId){const idx=planItems.value.findIndex(p=>p.id===planDlg.editingId);if(idx>=0)planItems.value[idx]={...planItems.value[idx],...planDlg.form}}else{planItems.value.push({id:Date.now(),...planDlg.form,semester:'2025-2026-2',status:'进行中'})};planDlg.show=false}
function openAdvisor(){advisorChanges.value.unshift({date:new Date().toISOString().split('T')[0],old:'李教授',new:'',reason:'',status:'审核中'})}
</script>
<style scoped>.page-section{max-width:1000px}</style>
